//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tProduct
    {
        public int fId { get; set; }


        [DisplayName("商品編號")]
        [Required]
        public string fPId { get; set; }


        [DisplayName("商品名稱")]
        [Required]
        public string fName { get; set; }


        [DisplayName("販售價格")]
        [Required]
        public Nullable<int> fPrice { get; set; }


        public string fImg { get; set; }


        [DisplayName("學院")]
        [Required]
        public string ffaculty { get; set; }


        [DisplayName("學系")]
        [Required]
        public string fdepartment { get; set; }


        public byte[] fImages { get; set; }


        public Nullable<int> fstate { get; set; }


        public string fcId { get; set; }


        [DisplayName("聯絡資訊")]
        [Required]
        public string fEmail { get; set; }


        [DisplayName("備註")]
        public string fsgtxt { get; set; }


        [DisplayName("ISBN碼")]
        [Required]
        public string fisbn { get; set; }

        [DisplayName("年級")]
        [Required]
        public string fclass { get; set; }


        [DisplayName("原價")]
        [Required]
        public Nullable<int> fPrice_s { get; set; }


        public string fUId { get; set; }


        public string fsell { get; set; }


        [DisplayName("LineID")]
        [Required]
        public string fLine { get; set; }
    }
}